
name: ci

# Controls when the workflow will run

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


workflow_dispatch:

env:
  IMAGE_NAME: 'tailt1223/tnt-web'
  CONTAINER_NAME: 'tnt-web'

jobs:
  build_and_push_to_docker_hub:
    runs-on: ubuntu-latest


    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tnt-web:latest


  deploy_to_digital_ocean:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub


    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          envs: CONTAINER_NAME, IMAGE_NAME
          script: |
            docker stop $(echo $CONTAINER_NAME) && docker rm $(echo $CONTAINER_NAME)
            docker run --name $(echo $CONTAINER_NAME) -p 9000:9000 -d $(echo $IMAGE_NAME)

